# Generated by Django 5.0.3 on 2024-04-03 07:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=255)),
                ("news_description", ckeditor.fields.RichTextField()),
                ("news_image", models.ImageField(upload_to="news/")),
                ("news_content", ckeditor.fields.RichTextField()),
                ("news_pub_date", models.DateTimeField(auto_now_add=True)),
                ("news_view", models.IntegerField(default=0)),
                (
                    "news_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_news.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News",
                "db_table": "news",
            },
        ),
    ]
