# Generated by Django 5.0.3 on 2024-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_text",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
