# Generated by Django 5.0.3 on 2024-04-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0002_news_news_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="news_text",
        ),
    ]
